// Generated by engineering-ruleset-plugin. Re-run the sync to update it;
// local edits are overwritten.
// Verifies that a PR's changed files stay within the scope of its linked
// issue-tracker ticket (ClickUp or Jira). Runs inside GitHub Actions.
// Requires Node 18+ (global fetch).
//
// It: (1) finds the ticket id from the PR (link, marker, or branch name),
// (2) pulls the ticket title + description from the tracker, (3) fetches the
// PR's changed files + diff from GitHub, (4) asks an AI whether the changes are
// in scope, (5) posts a sticky comment and exits 0 (pass) or 1 (block).
//
// Issue tracker is selected with ISSUE_PROVIDER: "clickup" (default) | "jira".
// AI provider is selected with AI_PROVIDER: "openrouter" (default) | "gemini" |
// "github-models".

import { appendFileSync } from 'node:fs';

const {
  GITHUB_TOKEN,
  GITHUB_API_URL = 'https://api.github.com',
  GITHUB_STEP_SUMMARY,
  REPO,                                   // "owner/name"
  PR_NUMBER,

  // ---- AI provider ----
  AI_PROVIDER = 'openrouter',      // "openrouter" | "github-models" | "gemini"
  AI_MODEL = 'qwen/qwen3-coder',   // OpenRouter model id (no "openrouter/" prefix)
  OPENROUTER_API_KEY,
  GEMINI_API_KEY,

  // ---- issue tracker ----
  ISSUE_PROVIDER = 'clickup',      // "clickup" | "jira"

  // ClickUp
  CLICKUP_TOKEN,

  // Jira (Atlassian Cloud)
  JIRA_BASE_URL,                          // e.g. https://your-org.atlassian.net
  JIRA_EMAIL,                             // Atlassian account email
  JIRA_API_TOKEN,                         // https://id.atlassian.com/manage-profile/security/api-tokens

  // Optional override for id extraction; capture group 1 = id
  ISSUE_ID_REGEX,

  // ---- behaviour ----
  REQUIRE_TASK = 'true',                  // block if no ticket is found
  FAIL_OPEN_ON_ERROR = 'false',           // if the AI/API errors, block (false) or pass (true)
  MAX_DIFF_CHARS = '60000',               // cap the diff sent to the model
  AUTO_CLOSE_OUT_OF_SCOPE = 'true',       // close the PR automatically on an out_of_scope verdict
} = process.env;

const [OWNER, NAME] = (REPO || '').split('/');
const COMMENT_MARKER = '<!-- pr-scope-check -->';
const requireTask = REQUIRE_TASK === 'true';
const failOpen = FAIL_OPEN_ON_ERROR === 'true';
const maxDiff = parseInt(MAX_DIFF_CHARS, 10) || 60000;
const autoClose = AUTO_CLOSE_OUT_OF_SCOPE === 'true';
const provider = (ISSUE_PROVIDER || 'clickup').toLowerCase();

// ---------------------------------------------------------------- GitHub API
async function gh(path, { method = 'GET', body } = {}) {
  const res = await fetch(`${GITHUB_API_URL}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    throw new Error(`GitHub ${method} ${path} -> ${res.status}: ${(await res.text()).slice(0, 400)}`);
  }
  return res.json();
}

const getPR = () => gh(`/repos/${OWNER}/${NAME}/pulls/${PR_NUMBER}`);
const closePR = () => gh(`/repos/${OWNER}/${NAME}/pulls/${PR_NUMBER}`, { method: 'PATCH', body: { state: 'closed' } });

async function getChangedFiles() {
  const files = [];
  for (let page = 1; page <= 3; page++) {
    const batch = await gh(`/repos/${OWNER}/${NAME}/pulls/${PR_NUMBER}/files?per_page=100&page=${page}`);
    files.push(...batch);
    if (batch.length < 100) break;
  }
  return files;
}

// ======================================================= ISSUE ID EXTRACTION
// ClickUp default task ids look like "86d3bzhgq": a short alphanumeric token
// mixing lowercase letters and digits.
// Jira issue keys look like "PROJ-123": uppercase project key + dash + number.

const hasLetterAndDigit = (s) => /[a-z]/i.test(s) && /\d/.test(s);

function extractClickUpId(pr) {
  const ID = '[0-9a-z]{6,12}';
  const branch = pr.head?.ref || '';
  const title = pr.title || '';
  const body = pr.body || '';
  const blob = `${body}\n${title}\n${branch}`;
  const titleBody = `${body}\n${title}`;

  // 1) A ClickUp link (most reliable): app.clickup.com/t/<id> or .../t/<teamId>/<id>
  const urlRe = new RegExp(`https?://(?:app|sharing)\\.clickup\\.com/t/(?:[0-9]+/)?(${ID})`, 'gi');
  for (const m of blob.matchAll(urlRe)) return { taskId: m[1].toLowerCase(), source: 'clickup-link' };

  // 2) A marked reference: #86d3bzhgq, [86d3bzhgq], "clickup: 86d3bzhgq", "CU-86d3bzhgq"
  const markRe = new RegExp(`(?:#|\\[|cu-|clickup[:\\s-]+)(${ID})`, 'gi');
  for (const m of titleBody.matchAll(markRe)) {
    if (hasLetterAndDigit(m[1])) return { taskId: m[1].toLowerCase(), source: 'marker' };
  }

  // 3) A task id in the branch name: 86d3bzhgq-add-login, alice/86d3bzhgq_fix, etc.
  const branchRe = new RegExp(`(?:^|[-_/])(${ID})(?=[-_/]|$)`, 'gi');
  for (const m of branch.matchAll(branchRe)) {
    if (hasLetterAndDigit(m[1])) return { taskId: m[1].toLowerCase(), source: 'branch-name' };
  }
  return null;
}

function extractJiraId(pr) {
  // Jira issue key: 2+ uppercase letters/digits starting with a letter, dash, number.
  const KEY = '[A-Z][A-Z0-9]+-\\d+';
  const branch = pr.head?.ref || '';
  const title = pr.title || '';
  const body = pr.body || '';
  const titleBodyBranch = `${body}\n${title}\n${branch}`;

  // 1) A Jira browse link: <base>/browse/PROJ-123
  const urlRe = new RegExp(`atlassian\\.net/browse/(${KEY})`, 'g');
  for (const m of titleBodyBranch.matchAll(urlRe)) return { taskId: m[1], source: 'jira-link' };

  // 2) Any bare issue key anywhere (title, body, branch). Uppercase so it's specific.
  const keyRe = new RegExp(`(?:^|[^A-Z0-9])(${KEY})(?![A-Z0-9])`, 'g');
  const upper = titleBodyBranch.toUpperCase();
  for (const m of upper.matchAll(keyRe)) return { taskId: m[1], source: 'issue-key' };
  return null;
}

function extractIssueId(pr) {
  // Optional override wins if provided.
  if (ISSUE_ID_REGEX) {
    try {
      const blob = `${pr.body || ''}\n${pr.title || ''}\n${pr.head?.ref || ''}`;
      const m = blob.match(new RegExp(ISSUE_ID_REGEX, 'i'));
      if (m) return { taskId: m[1] || m[0], source: 'custom-regex' };
    } catch (e) {
      console.error(`Invalid ISSUE_ID_REGEX: ${e.message}`);
    }
  }
  return provider === 'jira' ? extractJiraId(pr) : extractClickUpId(pr);
}

// ============================================================ ISSUE FETCHING
async function getClickUpTask(taskId) {
  if (!CLICKUP_TOKEN) throw new Error('CLICKUP_TOKEN is not set.');
  const res = await fetch(`https://api.clickup.com/api/v2/task/${encodeURIComponent(taskId)}`, {
    headers: { Authorization: CLICKUP_TOKEN },
  });
  if (!res.ok) throw new Error(`ClickUp API ${res.status} for task ${taskId}: ${(await res.text()).slice(0, 400)}`);
  const task = await res.json();
  const description = (task.description || task.text_content || '').trim();
  return {
    id: task.id,
    name: task.name || '(no title)',
    description: description.slice(0, 6000) || '(no description)',
    url: task.url || `https://app.clickup.com/t/${task.id}`,
  };
}

// Flatten Atlassian Document Format (ADF) description into plain text.
function adfToText(node) {
  if (!node) return '';
  if (typeof node === 'string') return node;
  if (node.type === 'text') return node.text || '';
  const children = (node.content || []).map(adfToText).join('');
  // add line breaks after block-ish nodes
  if (['paragraph', 'heading', 'listItem', 'blockquote'].includes(node.type)) return children + '\n';
  if (node.type === 'hardBreak') return '\n';
  return children;
}

async function getJiraTask(issueKey) {
  if (!JIRA_BASE_URL || !JIRA_EMAIL || !JIRA_API_TOKEN) {
    throw new Error('Jira requires JIRA_BASE_URL, JIRA_EMAIL and JIRA_API_TOKEN.');
  }
  const base = JIRA_BASE_URL.replace(/\/$/, '');
  const auth = Buffer.from(`${JIRA_EMAIL}:${JIRA_API_TOKEN}`).toString('base64');
  const res = await fetch(`${base}/rest/api/3/issue/${encodeURIComponent(issueKey)}?fields=summary,description`, {
    headers: { Authorization: `Basic ${auth}`, Accept: 'application/json' },
  });
  if (!res.ok) throw new Error(`Jira API ${res.status} for issue ${issueKey}: ${(await res.text()).slice(0, 400)}`);
  const issue = await res.json();
  const desc = issue.fields?.description;
  const text = (typeof desc === 'string' ? desc : adfToText(desc)).trim();
  return {
    id: issue.key,
    name: issue.fields?.summary || '(no title)',
    description: text.slice(0, 6000) || '(no description)',
    url: `${base}/browse/${issue.key}`,
  };
}

const getIssue = (id) => (provider === 'jira' ? getJiraTask(id) : getClickUpTask(id));

// --------------------------------------------------------------- Diff / files
function buildDiff(files) {
  let diff = '';
  let truncated = false;
  for (const f of files) {
    const header = `\n### ${f.filename}  (${f.status}, +${f.additions}/-${f.deletions})\n`;
    const patch = f.patch ? f.patch + '\n' : '(no textual diff — binary or too large)\n';
    if (diff.length + header.length + patch.length > maxDiff) {
      truncated = true;
      break;
    }
    diff += header + patch;
  }
  if (truncated) diff += '\n... [diff truncated to fit the model context] ...\n';
  return diff.trim() || '(no diff available)';
}

const fileList = (files) =>
  files.map((f) => `- ${f.filename} (${f.status}, +${f.additions}/-${f.deletions})`).join('\n');

// --------------------------------------------------------------- AI prompting
const SYSTEM_PROMPT = `You are a strict senior code reviewer whose only job is to decide whether a pull request stays within the scope of its assigned task.

You are given a task (title + description) that defines the intended work, the list of files changed in a pull request, and a truncated unified diff.

Rules:
- IN SCOPE: changes that implement, fix, test, document, or directly support the task's stated goal. Reasonable incidental changes are in scope: updating imports, types, small config, or tests needed to make the change work.
- OUT OF SCOPE: changes to unrelated features, files, or systems the task neither mentions nor implies; opportunistic edits, unrelated refactors, drive-by dependency bumps, or config changes unrelated to the task.
- Judge by intent and relevance, not filenames alone. If the task is vague, lean lenient but still flag clearly unrelated changes.

Respond with ONLY a JSON object (no markdown, no prose) with EXACTLY this shape:
{
  "verdict": "in_scope" | "out_of_scope",
  "confidence": <number between 0 and 1>,
  "summary": "<one sentence>",
  "out_of_scope_files": ["<path>", ...],
  "reasoning": "<2-4 sentences>"
}`;

function buildUserPrompt({ task, pr, files, diff }) {
  return `## Ticket (defines the intended scope)
Ticket ID: ${task.id}
Title: ${task.name}
Description:
${task.description}

## Pull request
Link: ${pr.html_url}
Title: ${pr.title}
Branch: ${pr.head?.ref} -> ${pr.base?.ref}

## Files changed (${files.length})
${fileList(files)}

## Unified diff
${diff}`;
}

async function callGitHubModels(system, user, model) {
  const res = await fetch('https://models.github.ai/inference/chat/completions', {
    method: 'POST',
    headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model,
      temperature: 0,
      response_format: { type: 'json_object' },
      messages: [
        { role: 'system', content: system },
        { role: 'user', content: user },
      ],
    }),
  });
  if (!res.ok) throw new Error(`GitHub Models ${res.status}: ${(await res.text()).slice(0, 500)}`);
  const data = await res.json();
  return data.choices?.[0]?.message?.content || '';
}

async function callGemini(system, user, model) {
  const m = model && !model.startsWith('openai/') ? model : 'gemini-2.5-flash';
  const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${m}:generateContent`, {
    method: 'POST',
    headers: { 'x-goog-api-key': GEMINI_API_KEY, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      system_instruction: { parts: [{ text: system }] },
      contents: [{ role: 'user', parts: [{ text: user }] }],
      generationConfig: { temperature: 0, responseMimeType: 'application/json', maxOutputTokens: 2048 },
    }),
  });
  if (!res.ok) throw new Error(`Gemini ${res.status}: ${(await res.text()).slice(0, 500)}`);
  const data = await res.json();
  const finish = data.candidates?.[0]?.finishReason;
  const text = (data.candidates?.[0]?.content?.parts || []).map((p) => p.text || '').join('');
  if (finish && finish !== 'STOP') console.error(`Gemini finishReason=${finish} (possible truncation)`);
  return text;
}

async function callOpenRouter(system, user, model) {
  const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${OPENROUTER_API_KEY}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': `https://github.com/${REPO}`,
      'X-Title': 'PR Scope Check',
    },
    body: JSON.stringify({
      model,
      temperature: 0,
      max_tokens: 2048,
      response_format: { type: 'json_object' },
      messages: [
        { role: 'system', content: system },
        { role: 'user', content: user },
      ],
    }),
  });
  if (!res.ok) throw new Error(`OpenRouter ${res.status}: ${(await res.text()).slice(0, 500)}`);
  const data = await res.json();
  const finish = data.choices?.[0]?.finish_reason;
  if (finish && finish !== 'stop') console.error(`OpenRouter finish_reason=${finish} (possible truncation)`);
  return data.choices?.[0]?.message?.content || '';
}

function askAI(system, user) {
  if (AI_PROVIDER === 'openrouter') {
    if (!OPENROUTER_API_KEY) throw new Error('AI_PROVIDER=openrouter but OPENROUTER_API_KEY is not set.');
    return callOpenRouter(system, user, AI_MODEL);
  }
  if (AI_PROVIDER === 'gemini') {
    if (!GEMINI_API_KEY) throw new Error('AI_PROVIDER=gemini but GEMINI_API_KEY is not set.');
    return callGemini(system, user, AI_MODEL);
  }
  return callGitHubModels(system, user, AI_MODEL);
}

function parseVerdict(text) {
  let t = (text || '').trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
  try { return JSON.parse(t); } catch { /* fall through */ }
  const m = t.match(/\{[\s\S]*?\}(?=\s*$|\s*[\r\n])/) || t.match(/\{[\s\S]*\}/);
  if (m) { try { return JSON.parse(m[0]); } catch { /* fall through */ } }
  return null;
}

// ------------------------------------------------------------- Sticky comment
async function upsertComment(bodyMd) {
  const body = `${COMMENT_MARKER}\n${bodyMd}`;
  const comments = await gh(`/repos/${OWNER}/${NAME}/issues/${PR_NUMBER}/comments?per_page=100`);
  const existing = comments.find((c) => (c.body || '').includes(COMMENT_MARKER));
  if (existing) {
    await gh(`/repos/${OWNER}/${NAME}/issues/comments/${existing.id}`, { method: 'PATCH', body: { body } });
  } else {
    await gh(`/repos/${OWNER}/${NAME}/issues/${PR_NUMBER}/comments`, { method: 'POST', body: { body } });
  }
}

const footer = `\n\n<sub>Automated scope check · ${provider} · ${AI_PROVIDER} · ${AI_MODEL}</sub>`;

function summary(md) {
  if (GITHUB_STEP_SUMMARY) { try { appendFileSync(GITHUB_STEP_SUMMARY, md + '\n'); } catch { /* ignore */ } }
}

// How to link a ticket, phrased per provider (used in the "no ticket" message).
function howToLink() {
  if (provider === 'jira') {
    return (
      `- Put the issue key in the branch name, e.g. \`PROJ-123-add-login\`\n` +
      `- Or put it in the PR title, e.g. \`[PROJ-123] Add login\`\n` +
      `- Or paste the issue link in the description, e.g. \`https://your-org.atlassian.net/browse/PROJ-123\``
    );
  }
  return (
    `- Paste the task link in the PR description, e.g. \`https://app.clickup.com/t/86d3bzhgq\`\n` +
    `- Or start the branch name with the task id, e.g. \`86d3bzhgq-add-login\`\n` +
    `- Or put the id in the title, e.g. \`[86d3bzhgq] Add login\``
  );
}

// ----------------------------------------------------------------------- main
async function main() {
  if (!OWNER || !NAME || !PR_NUMBER) throw new Error('Missing REPO or PR_NUMBER env vars.');

  const pr = await getPR();
  const ref = extractIssueId(pr);

  if (!ref) {
    const md =
      `### 🚫 Scope check — no ticket linked\n\n` +
      `I couldn't find a ${provider} ticket id for this PR, so I can't verify whether the changes are in scope.\n\n` +
      `Do one of these, then push again:\n${howToLink()}` + footer;
    await upsertComment(md);
    if (requireTask) { console.log('::error::No ticket linked.'); process.exit(1); }
    console.log('::notice::No ticket linked; REQUIRE_TASK=false so passing.');
    process.exit(0);
  }

  const task = await getIssue(ref.taskId);
  console.log(`Linked ticket: ${task.name} (${task.id}) via ${ref.source}`);

  const files = await getChangedFiles();
  if (files.length === 0) {
    await upsertComment(`### ✅ Scope check passed\n\nNo files changed to review.` + footer);
    process.exit(0);
  }

  const diff = buildDiff(files);
  const raw = await askAI(SYSTEM_PROMPT, buildUserPrompt({ task, pr, files, diff }));
  const v = parseVerdict(raw);
  if (!v || !v.verdict) throw new Error(`AI returned unparseable output: ${String(raw).slice(0, 300)}`);

  const inScope = v.verdict === 'in_scope';
  const pct = Math.round((Number(v.confidence) || 0) * 100);
  const taskLink = `[${task.name}](${task.url}) (\`${task.id}\`)`;

  let md;
  if (inScope) {
    md =
      `### ✅ Scope check passed\n\n` +
      `**Ticket:** ${taskLink}\n\n` +
      `${v.summary || 'Changes appear to be within scope.'} _(confidence ${pct}%)_` + footer;
  } else {
    const flagged = (v.out_of_scope_files || []).map((f) => `- \`${f}\``).join('\n');
    const closingNote = autoClose
      ? `This PR has been **closed automatically**. Remove the unrelated changes, or update the ticket ` +
        `description to cover this work, then open a new PR.`
      : `Remove the unrelated changes, or update the ticket description to cover this work, ` +
        `then push again — this check re-runs automatically.`;
    md =
      `### 🚫 Scope check failed — merge blocked\n\n` +
      `**Ticket:** ${taskLink}\n` +
      `**Verdict:** Out of scope _(confidence ${pct}%)_\n\n` +
      `${v.reasoning || v.summary || ''}\n\n` +
      (flagged ? `**Files flagged as out of scope:**\n${flagged}\n\n` : '') +
      closingNote + footer;
  }

  await upsertComment(md);
  summary(md.replace(footer, ''));

  if (inScope) { console.log('::notice::Scope check passed.'); process.exit(0); }

  if (autoClose) {
    await closePR();
    console.log('::error::Scope check failed — changes out of scope. PR closed automatically.');
  } else {
    console.log('::error::Scope check failed — changes out of scope.');
  }
  process.exit(1);
}

main().catch(async (e) => {
  console.error(e);
  try {
    if (failOpen) {
      await upsertComment(
        `### ⚠️ Scope check skipped (error)\n\nThe check errored but \`FAIL_OPEN_ON_ERROR=true\`, ` +
        `so the PR is not blocked.\n\n\`\`\`\n${e.message}\n\`\`\`` + footer,
      );
      console.log('::warning::Scope check errored; passing due to FAIL_OPEN_ON_ERROR=true.');
      process.exit(0);
    }
    await upsertComment(
      `### ⚠️ Scope check couldn't complete — merge blocked\n\n` +
      `The automated check hit an error and is blocking the merge as a precaution:\n\n` +
      `\`\`\`\n${e.message}\n\`\`\`\n\n` +
      `Fix the issue and re-run, or set \`FAIL_OPEN_ON_ERROR=true\` to let PRs through on errors.` + footer,
    );
  } catch (e2) {
    console.error('Also failed to post the comment:', e2);
  }
  process.exit(1);
});
